server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:32766/db_users
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  ######### Email properties #########
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    username: fitness.studio@mail.ru
    password: XfzLjXqC6NDELuR7fHhs
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            ssl: TLSv1.2
    protocol: smtp
    test-connection: false
    debug: true

  security:
    jwt:
      token:
        secret: "fitness"
        expiration: 6085000



  main:
    allow-circular-references: true










